# Generated by Django 3.0.8 on 2021-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(editable=False, max_length=32)),
                ('name', models.CharField(max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
