# Generated by Django 3.0.8 on 2021-03-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_assessment',
        ),
    ]
