# Generated by Django 3.0.8 on 2021-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
