# Generated by Django 3.0.8 on 2021-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210323_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_views',
            field=models.IntegerField(default=0),
        ),
    ]
